"""Chinese UI labels for report rendering."""

from __future__ import annotations

ZH_LABELS = {
    "Candidates": "候选项目",
    "Breakout": "趋势突破",
    "Valuable Mature": "高价值成熟项目",
    "Watchlist": "观察名单",
    "Noise / Filtered": "已过滤信号",
    "Multi Source": "多源命中",
    "Recent Acceleration": "近期升温",
    "Long-term Value": "长期价值",
    "Worth Watching": "值得观察",
    "Filtered": "已过滤",
    "Read": "阅读",
    "Watch": "观察",
    "Ignore": "忽略",
    "Deep Research": "深研",
    "Try Locally": "本地试用",
    "Language": "语言",
    "Stars": "Star",
    "Forks": "Fork",
    "Pushed": "最近更新",
    "Core Idea": "核心思路",
    "Technical Value": "技术价值",
    "Why It Matters": "关注原因",
    "Enterprise Fit": "企业适配",
    "Risks": "风险",
    "Noise Reasons": "过滤原因",
    "Rule Scored": "规则评分",
    "LLM Calibrated": "LLM 校准",
    "Snapshot": "数据快照",
    "Model": "模型",
    "Generated by": "生成工具",
    "GitHub AI Trend Radar": "GitHub AI 开源趋势雷达",
}

ACTION_ZH = {
    "ignore": "忽略",
    "watch": "观察",
    "read": "阅读",
    "deep_research": "深研",
    "try_locally": "本地试用",
}

BUCKET_ZH = {
    "breakout": "趋势突破",
    "valuable_mature": "高价值成熟项目",
    "watchlist": "观察名单",
    "noise": "已过滤信号",
}

TOPIC_ZH = {
    "ai_agent": "AI Agent",
    "mcp": "MCP / 模型上下文协议",
    "coding_agent": "Coding Agent / 软件工程智能体",
    "rag_knowledge": "RAG / 知识库",
    "llm_infra": "LLM Infra / 模型基础设施",
    "vector_database": "Vector DB / 向量检索",
    "gui_computer_use": "GUI Agent / Computer Use",
    "physical_ai": "Physical AI / 物理世界智能",
    "embodied_ai": "Embodied AI / 具身智能",
    "edge_on_device_ai": "端侧 / 边缘 AI",
    "ambient_iot_ai": "Ambient / IoT AI",
    "personal_world_model": "Personal World Model / 个人世界模型",
}


def zh_label(key: str, default: str | None = None) -> str:
    return ZH_LABELS.get(key, default or key)


def topic_label(topic: str) -> str:
    return TOPIC_ZH.get(str(topic), str(topic))
